name: module3_task0
on:
  push:
  schedule:
    - cron: "0 0 * * *"
jobs:
  module3_task0:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: cd module3_task0 && make help
