name: module3_task2
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  module3_task2:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      # Required tools are installed prior to any make target
      - name: Run setup.sh script
        run: sudo module3_task2/setup.sh

      - name: Build the application
        run: cd module3_task2 && make build

      # Check expected behaviour of the app (tests)
      - name: Run unit-tests
        run: cd module3_task2 && make unit-tests

      - name: Run integration-tests
        run: cd module3_task2 && make integration-tests

      - name: Run validate
        run: cd module3_task2 && make validate

      # Shows help message
      - name: help
        run: cd module3_task2 && make help

      # Check markdowns and golangci-lint
      - name: lint
        run: cd module3_task2 && make lint

      # Zip file that contains the needed files to deply the website
      - name: package
        run: cd module3_task2 && make package

      - uses: actions/upload-artifact@v3
        with:
          name: awesome-website
          path: ./module3_task2/awesome-website.zip
